### PR TITLE
[BUGFIX] Revert changes on `errorAction` to fix #1082

### LINKED ISSUE #1082: [BUG] New Tenant errors
## Description

Clicking on an non cofig-folder shows following error: `Validation failed while trying to call Kitodo\Dlf\Controller\Backend\NewTenantController->errorAction(). ` which then shows following error on the configuration folder: `An error occurred while trying to call Kitodo\Dlf\Controller\Backend\NewTenantController->errorAction()`

Edit: now it got this message additionally `Return value of Kitodo\Dlf\Controller\Backend\NewTenantController::errorAction() must be an instance of Psr\Http\Message\ResponseInterface, string returned`

## Reproduction

Steps to reproduce the behaviour:

0. Get newest code (in my case 4dd7001b643607fb879c006288e8aa3a139fd5d0)
1. Go to BE -> New Tenant -> click on any page or non presentation config folder:
    * grafik
2. Go to BE -> New Tenant -> click on your presentation config folder:
    * grafik

## Environment

 -  OS version: Debian (in Docker)
 -  RDBMS version: Maria DB (MySQL 5.5.5-10.11.2-MariaDB-1:10.11.2+maria~ubu2204)
 -  Apache Solr version: -
 -  TYPO3 version: 10.4.38-dev
 -  PHP version: 7.4.33

### PR DESCRIPTION
**Pull request by csidirop**
Fix for #1082

### CODE REVIEW

**Comment by beatrycze-volk** [comment]
Please add comment that this change is made to keep it compatible with TYPO3 10, but in the moment of migration to TYPO3 11 this change must be again reverted (as explained here https://github.com/kitodo/kitodo-presentation/pull/1091)

File: Classes/Controller/Backend/NewTenantController.php [hunk 1]
```diff
@@ -442,11 +442,13 @@ public function indexAction(): void
...
-     * @return ResponseInterface
+     * @return void
      */
-    public function errorAction(): ResponseInterface
+    // @phpstan-ignore-next-line
+    public function errorAction(): void
     {
-        return parent::errorAction();
+        // TODO revert when migriting to TYPO3 11
+        // (this change is made to keep it compatible with TYPO3 10)
```
Comment (sebastian-meyer) [inline Classes/Controller/Backend/NewTenantController.php]:
```suggestion
        // TODO: Call parent::errorAction() when dropping support for TYPO3 v10.
```

**Review by sebastian-meyer — CHANGES_REQUESTED** [review]

**Review by sebastian-meyer — APPROVED** [review]
