### PR TITLE
[BUGFIX] Generate database documentation via typo3 command

### LINKED ISSUE #1437: [BUG] Running `composer docs:db` fails
## Description

Several documentation files were build using `composer docs:db`, but this command no longer works with the latest main branch installed on TYPO3 v11.

The command tries to execute `Build/Documentation/dbdocs/generate.php` which fails to find `vendor/autoload.php` (might require different paths for TYPO3 v11 and TYPO3 v12 or later).

### PR DESCRIPTION
**Pull request by thomaslow**
Fixes #1437

This pull request moves the `Build/Documentation/dbdocs` code to the `Classes/Command/DbDocs` directory and uses a typo3 command (instead of a composer script) to trigger the generation of the rst file `Documentation/Developers/Database.rst`.

Todo
- [x] generated rst file does not include general table description

### CODE REVIEW

File: Classes/Command/DbDocs/RstSection.php [hunk 1]
```diff
@@ -10,7 +10,7 @@
  * LICENSE.txt file that was distributed with this source code.
  */
 
-namespace Kitodo\DbDocs;
+ namespace Kitodo\Dlf\Command\DbDocs;
```
Comment (sebastian-meyer) [inline Classes/Command/DbDocs/RstSection.php]:
```suggestion
namespace Kitodo\Dlf\Command\DbDocs;
```

**Review by sebastian-meyer — CHANGES_REQUESTED** [review]

**Review by sebastian-meyer — APPROVED** [review]

File: Classes/Command/DbDocs/Generator.php [hunk 2]
```diff
@@ -87,7 +83,7 @@ public function injectConfigurationManager(ConfigurationManager $configurationMa
 
     public function __construct()
     {
-
+        $this->languageService = GeneralUtility::makeInstance(LanguageService::class);
```
Comment (stweil) [inline Classes/Command/DbDocs/Generator.php:86]: @thomaslow, this line throws a runtime exception when I run `vendor/bin/typo3 kitodo:dbdocs`:
```
Exception has occurred.
ArgumentCountError: Too few arguments to function TYPO3\CMS\Core\Localization\LanguageService::__construct(), 0 passed in /typo3_12/vendor/typo3/cms-core/Classes/Utility/GeneralUtility.php on line 2985 and exactly 3 expected
```
