### PR TITLE
[BUGFIX] Re-introduce search for coordinates in ol.Feature Array

### LINKED ISSUE #20: [BUG] re-searching for a word fails highlighting on trarget page
relates to branch: https://github.com/fschoelzel/ddb_kitodo_zeitungsportal/tree/dlf-5

After searching for a word and follow the link to the site in the document, the re-search on the target page removes the highlighting of the words. 

expected behavior:
re-searched words on target page should be re-highlighted again.

### PR DESCRIPTION
**Pull request by fschoelzel**
Rewrite displayHighlightWord to represent overwritable forward-function to utility.js
fixes: [slub#20](https://github.com/slub/ddb_kitodo_zeitungsportal/issues/20)

### CODE REVIEW

File: Resources/Public/JavaScript/PageView/PageView.js [hunk 1]
```diff
@@ -734,6 +734,18 @@ dlfViewer.prototype.createControl = function(controlName, layers) {
...
+/**
+ * Forwards the search to dlfUtils.searchFeatureCollectionForWords
+ *
+ * @param {Array.<ol.Feature>} stringFeatures - Array of features containing text information
+ * @param {string} value - Search term
+ * @returns {Array.<ol.Feature>|undefined} Array of OpenLayers features containing found words
+ * @see dlfUtils.searchFeatureCollectionForWords
+ */
+dlfViewer.prototype.searchFeatures = function(stringFeatures, value) {
+  return dlfUtils.searchFeatureCollectionForWords(stringFeatures, value);
```
Comment (beatrycze-volk) [inline Resources/Public/JavaScript/PageView/PageView.js:746]: But is not in this case the function `searchFeatureCollectionForCoordinates` unused? Or is the ddb-zeitunsportal using it?

File: Resources/Public/JavaScript/PageView/PageView.js [hunk 2]
```diff
@@ -786,23 +798,23 @@ dlfViewer.prototype.displayHighlightWord = function(highlightWords = null) {
...
-        var self = this;
-        var values = decodeURIComponent(this.highlightWords).split(';');
+        const self = this;
+        const values = decodeURIComponent(this.highlightWords).split(';');
 
         $.when.apply($, this.fulltextsLoaded_)
-            .done(function (fulltextData, fulltextDataImageTwo) {
-                var stringFeatures = [];
+            .done((fulltextData, fulltextDataImageTwo) => {
+                const stringFeatures = [];
```
Comment (beatrycze-volk) [inline Resources/Public/JavaScript/PageView/PageView.js:806]: Can `stringFeatures` be changed in line `Array.prototype.push.apply(stringFeatures, data.getStringFeatures()); ` after they have been defined as `const` here?

File: Resources/Public/JavaScript/PageView/PageView.js (hunk 1 above)
Comment (fschoelzel) [reply Resources/Public/JavaScript/PageView/PageView.js:746]: Yes, in this case I override `searchFeatures()` in  ddb-zeitunsportal with `searchFeatureCollectionForCoordinates()`
So i don't have to override and maintain the whole `displayHighlightWord()` function.

File: Resources/Public/JavaScript/PageView/PageView.js (hunk 2 above)
Comment (fschoelzel) [reply Resources/Public/JavaScript/PageView/PageView.js:806]: Yes, the push() method will work in this case. It still can change the content of the array.

**Review by beatrycze-volk — APPROVED** [review]

**Review by sebastian-meyer — APPROVED** [review]
