### PR TITLE
Finish Solarium upgrade

### LINKED ISSUE #566: Bugs introduced with usage of Solarium 5.2.0 by #550
## Description

The change by #550 to Solarium 5.2.0 does not work:

1. Feedback in extension settings wrong
Sachsen Digital  TYPO3 CMS 9 5 23
The solrPath should be set to "/" but the flash feedback reports that the solr connection fails. This is wrong.

2. Collection Plugin cannot connect
The collection plugin fails with the famous error message `Call to a member function search_raw() on null`. As always this means there is no valid solr instance.

3. Indexing does'nt work
Does nothing without feedback. Normal behaviour if Solr ist not reachable.

4. New Solr cores cannot be created in backend
Does nothing without feedback. Normal behaviour if Solr ist not reachable.

## Reproduction

Try the steps above.

## Environment

 - Apache Solr version: 7.7.3
 - Solarium 5.2.0
 - TYPO3 version: 9.5.0

## Additional Context

Fix for 2., 3., and 4. is in `Kitodo\Dlf\Common\Solr::__construct()`. The leading and trailing slash around path is wrong. The` $this->service->ping($ping);` fails with it.

### PR DESCRIPTION
**Pull request by sebastian-meyer**
This pull requests finishes the Solarium upgrade from #550:

Use Solarium everywhere we communicate with Solr:
- [x] Fetching documents via `\Kitodo\Dlf\Common\DocumentList`
- [x] Indexing documents via `\Kitodo\Dlf\Common\Indexer`
- [x] Checking Solr connection via `\Kitodo\Dlf\Hooks\ConfigurationForm`
- [x] Adding new **or deleting** Solr cores via `\Kitodo\Dlf\Hooks\DataHandler`
- [x] Fetching documents via `\Kitodo\Dlf\Plugin\Collection`
- [x] Search queries via `\Kitodo\Dlf\Plugin\OaiPmh`
- [x] Search queries via `\Kitodo\Dlf\Plugin\Search`
- [x] Search queries via `\Kitodo\Dlf\Plugin\Eid\SearchInDocument`
- [x] Autocomplete queries via `\Kitodo\Dlf\Plugin\Eid\SearchSuggest`
- [x] Checking for Solr updates and recreating cores via `class.ext_update.php`

This should fix #566

### CODE REVIEW

**Comment by sebastian-meyer** [comment]
~~Even though the first commit message suggests otherwise, this doesn't upgrade Solarium to 5.2, but keeps the version introduced by @beatrycze-volk.~~
I actually updated the Solarium dependency to `^5.2` with f16209708e0ee4d2dfc0d197751fbe4aae6ed53f.

**Review by beatrycze-volk — DISMISSED** [review]

File: Classes/Plugin/Eid/SearchInDocument.php [hunk 1]
```diff
@@ -38,29 +38,48 @@ class SearchInDocument
...
+        // Perform Solr query.
+        $solr = Solr::getInstance($core);
+        if ($solr->ready) {
+            $query = $solr->service->createSelect();
+            $query->setFields(['id', 'uid', 'page']);
+            $query->setQuery('fulltext:(' . Solr::escapeQuery((string) $parameters['q']) . ') AND uid:' . intval($parameters['uid']));
+            $query->setStart($count)->setRows(20);
+            $hl = $query->getHighlighting();
+            $hl->setFields('fulltext');
+            $hl->setMethod('fastVector');
```
Comment (albig) [inline Classes/Plugin/Eid/SearchInDocument.php]: This method exists only from solarium 6.0.2.
Maybe, before it was possible with `$hl->setUsefastvectorhighlighter(true);`? Could'n test this because of non-ready solr above.

File: Classes/Plugin/Eid/SearchInDocument.php [hunk 2]
```diff
@@ -38,29 +38,48 @@ class SearchInDocument
...
-            $query = (string)$parameters['q'];
-            $uid = (string)$parameters['uid'];
-            $start = (string)$parameters['start'];
-            $url = trim(Solr::getSolrUrl($core), '/') . '/select?wt=json&q=fulltext:(' . Solr::escapeQuery($query) . ')%20AND%20uid:' . $uid
-                . '&hl=on&hl.fl=fulltext&fl=uid,id,page&hl.method=fastVector'
-                . '&start=' . $start . '&rows=20';
-            $output = GeneralUtility::getUrl($url);
+        // Perform Solr query.
+        $solr = Solr::getInstance($core);
+        if ($solr->ready) {
```
Comment (albig) [inline Classes/Plugin/Eid/SearchInDocument.php:55]: solr instance is not ready at this point.

$solr->config->path is empty. Should be "/".
$solr->config->timeout is 0. Should be 10.
Both is not set in the extension configuration.

File: Classes/Plugin/Eid/SearchInDocument.php [hunk 3]
```diff
@@ -38,29 +38,48 @@ class SearchInDocument
...
+            $results = $solr->service->select($query);
+            $output['numFound'] = $results->getNumFound();
+            $highlighting = $results->getHighlighting();
+            foreach ($results as $result) {
+                $snippet = $highlighting->getResult($result->id);
+                $document = [
+                    'id' => $result->id,
+                    'uid' => $result->uid,
+                    'page' => $result->page,
+                    'snippet' => $snippet['fulltext']
```
Comment (albig) [inline Classes/Plugin/Eid/SearchInDocument.php]: Cannot use object of type Solarium\Component\Result\Highlighting\Result as array

File: Classes/Hooks/DataHandler.php [hunk 4]
```diff
@@ -387,5 +349,53 @@ public function processCmdmap_postProcess($command, $table, $id)
...
+            if (count($allResults) == 1) {
+                $resArray = $allResults[0];
+                // Establish Solr connection.
+                $solr = Solr::getInstance();
+                if ($solr->ready) {
+                    // Delete Solr core.
+                    $query = $solr->service->createCoreAdmin();
+                    $action = $query->createUnload();
+                    $action->setCore($resArray['core']);
+                    $action->setDeleteDataDir(true);
```
Comment (albig) [inline Classes/Hooks/DataHandler.php]: Honeystly. I wouldn't add this feature. This can destroy the indexing work of several months by a wrong click in the backend. Or you move installation to another system and do not think about chaning the Solr configuration.
Deleting a solr core is a super admin job. So the person knows what he/she is doing and can do this even better in the Solr admin page.
If we add this feature to TYPO3, we need at least one of the following:
1. Possibility to disable this feature
2. Better do it in some backend-module
3. Add a dialog to confirm the deletion

**Review by albig — CHANGES_REQUESTED** [review]
The status of the solr connection seems to work in the extentension configuration. The searchInDocument-plugin fails. If this is fixed, I would check the autosuggestion and the other features.
The feature "delete core" is nice but very dangerious. I wouldn't implement it like this.

File: Classes/Plugin/Eid/SearchInDocument.php (hunk 1 above)
Comment (sebastian-meyer) [reply Classes/Plugin/Eid/SearchInDocument.php]: You're right! The method is called `setUseFastVectorHighlighter()` in Solarium <6.x.

File: Classes/Plugin/Eid/SearchInDocument.php (hunk 3 above)
Comment (sebastian-meyer) [reply Classes/Plugin/Eid/SearchInDocument.php]: Ah, `Solarium\Component\Result\Highlighting\Result` implements `\IteratorAggregate` and `\Countable`, but not `\ArrayAccess` for some reason...

File: Classes/Hooks/DataHandler.php (hunk 4 above)
Comment (sebastian-meyer) [reply Classes/Hooks/DataHandler.php]: I've added the first option: In order to automatically delete a Solr core when deleting the corresponding TYPO3 record, you have to set `solrAllowCoreDelete` to `true` in extension configuration (default is `false` to prevent accidents).

File: Classes/Plugin/Eid/SearchInDocument.php (hunk 2 above)
Comment (sebastian-meyer) [reply Classes/Plugin/Eid/SearchInDocument.php:55]: > $solr->config->path is empty. Should be "/".

This is actually correct. A single `/` is added in `Solr::__construct()` at line 640.

> $solr->config->timeout is 0. Should be 10.

Hm, that was a tricky one. In line 333 of `/Classes/Common/Solr.php` the timeout is set as:
`MathUtility::forceIntegerInRange($conf['solrTimeout'], 1, intval(ini_get('max_execution_time')), 10)`

So, if `$conf['timeout']` is not set in the extension configuration, a default value of `10` is set, but only if this value is between `1` and `max_execution_time`.

The tricky part is, that if you are using something like XDebug or a development environment which has `max_execution_time` disabled, `ini_get('max_execution_time')` will return `0`, thus forcing the timeout to be `0` as well.

I've changed this so that the timeout is limited to 30 seconds if `max_execution_time` is 0.

File: Resources/Public/Javascript/Search/SearchInDocument.js [hunk 5]
```diff
@@ -67,55 +64,61 @@ $(document).ready(function() {
...
-              var resultItems = [];
-              var resultList = '<div class="results-active-indicator"></div><ul>';
-              if (data.error) {
-                  resultList += '<li class="error">' + data.error + '</li>';
-              } else {
-                  for (var i=0; i < data.response.docs.length; i++) {
+                var resultItems = [];
+                var resultList = '<div class="results-active-indicator"></div><ul>';
+                var start = -1;
+                var results = JSON.parse(data);
```
Comment (albig) [inline Resources/Public/Javascript/Search/SearchInDocument.js]:
```suggestion
                var results = data;
```

Comment (albig) [reply Resources/Public/Javascript/Search/SearchInDocument.js]: `JSON.parse(data)` fails with the following message: _SyntaxError: Unexpected token o in JSON at position 1_.

It's because `data` is already a JavaScript object and no JSON at this point anymore.

See: https://stackoverflow.com/questions/38380462/syntaxerror-unexpected-token-o-in-json-at-position-1

File: Resources/Public/Javascript/Search/SearchInDocument.js [hunk 6]
```diff
@@ -67,55 +64,61 @@ $(document).ready(function() {
...
-                  }
-                  if (resultItems.length > 0) {
-                    // sort by page as this cannot be done with current solr schema
-                    resultItems.sort(function(a, b){return a-b});
-                    resultItems.forEach(function(item, index){
+                        if (element['snippet'].length > 0) {
+                            resultItems[element['page']] = '<span class="structure">'
+                                + $('#tx-dlf-search-in-document-label-page').text() + ' ' + element['page']
+                                + '</span><br />'
+                                + '<span ="textsnippet">' +
```
Comment (albig) [inline Resources/Public/Javascript/Search/SearchInDocument.js]:
```suggestion
                                + '<span ="textsnippet">' 
```

Comment (albig) [reply Resources/Public/Javascript/Search/SearchInDocument.js]: One `+` too much destroys the output.

File: Classes/Plugin/Eid/SearchInDocument.php (hunk 2 above)
Comment (albig) [reply Classes/Plugin/Eid/SearchInDocument.php:55]: Ahh, ok. So xdebug just spoofed me? Sorry for that. But without I wouldn't find the other bugs ;-)

File: Classes/Plugin/Eid/SearchInDocument.php [hunk 7]
```diff
@@ -38,29 +37,48 @@ class SearchInDocument
...
+        // Perform Solr query.
+        $solr = Solr::getInstance($core);
+        if ($solr->ready) {
+            $query = $solr->service->createSelect();
+            $query->setFields(['id', 'uid', 'page']);
+            $query->setQuery('fulltext:(' . Solr::escapeQuery((string) $parameters['q']) . ') AND uid:' . intval($parameters['uid']));
+            $query->setStart($count)->setRows(20);
+            $hl = $query->getHighlighting();
+            $hl->setFields(['fulltext']);
+            $hl->setUseFastVectorHighlighter(true);
```
Comment (albig) [inline Classes/Plugin/Eid/SearchInDocument.php:62]: Perfect. This does the job with Solarium < 6.

File: Classes/Plugin/Eid/SearchInDocument.php (hunk 1 above)
Comment (albig) [reply Classes/Plugin/Eid/SearchInDocument.php]: This works now.

File: Resources/Public/Javascript/Search/SearchInDocument.js (hunk 5 above)
Comment (sebastian-meyer) [reply Resources/Public/Javascript/Search/SearchInDocument.js]: I hate Javascript...

File: Resources/Public/Javascript/Search/SearchInDocument.js (hunk 6 above)
Comment (sebastian-meyer) [reply Resources/Public/Javascript/Search/SearchInDocument.js]: Did I mention I hate Javascript?

Comment (sebastian-meyer) [reply Resources/Public/Javascript/Search/SearchInDocument.js]: And why did no static code analyzer and syntax checker find this?

File: Classes/Hooks/DataHandler.php (hunk 4 above)
Comment (albig) [reply Classes/Hooks/DataHandler.php]: Perfect. This works as expected. The core is only deleted if this option is activated.

File: Resources/Public/Javascript/Search/SearchInDocument.js (hunk 6 above)
Comment (albig) [reply Resources/Public/Javascript/Search/SearchInDocument.js]: Don't know. Even the browser didn't complain but scrambels the output. There was some `NaNhttp://` instead of the `<a>`-tag.

Comment (sebastian-meyer) [reply Resources/Public/Javascript/Search/SearchInDocument.js]: I've fixed this with a29a7ca

File: Resources/Public/Javascript/Search/SearchInDocument.js (hunk 5 above)
Comment (sebastian-meyer) [reply Resources/Public/Javascript/Search/SearchInDocument.js]: I've (hopefully) fixed this with eaf0096

File: Resources/Public/Javascript/Search/Suggester.js [hunk 8]
```diff
@@ -31,14 +31,14 @@ $(
 					function(data) {
 						var result = [];
 						var option = "";
-						$("arr[name='suggestion'] str", data).each(function(i) {
+						data.each(function(i) {
```
Comment (albig) [inline Resources/Public/Javascript/Search/Suggester.js]: Uncaught TypeError: data.each is not a function

Comment (albig) [reply Resources/Public/Javascript/Search/Suggester.js]: But data is empty. Will dig deeper into it.

Comment (albig) [reply Resources/Public/Javascript/Search/Suggester.js]: The old code executed the following query (from Solr log):
```
  webapp=/solr path=/suggest params={q=dresde&wt=xml} status=0 QTime=2
```
--> 1 Result

The new code executes the following query:
```
webapp=/solr path=/suggest params={json.nl=flat&omitHeader=true&suggest.build=false&suggest.q=dresd&suggest.count=10&suggest.reload=false&suggest=true&suggest.dictionary=suggest&wt=json} status=0 QTime=0
```
--> 0 Results (of course on same core)

Comment (albig) [reply Resources/Public/Javascript/Search/Suggester.js]: I think the problem is, that we configure in solrconfig.xml the SpellCheckComponent as way to get a autosuggest feature. But we use the Suggester component. I assume, this is the better & newer way.

From https://lucene.apache.org/solr/guide/7_7/suggester.html: 

> Although it is possible to use the Spell Checking functionality to power autosuggest behavior, Solr has a dedicated SuggestComponent designed for this functionality.

So we get a spellchecking-response, if we do a query like:
```
/suggest?q=dresde&wt=json&omitHeader=true
{
  "spellcheck":{
    "suggestions":[
      "dresde",{
        "numFound":2,
        "startOffset":0,
        "endOffset":6,
        "suggestion":["dresden-leipziger schnellpressenfabrik ag, coswig",
          "dresdener pflasterstein-werke aktiengesellschaft, dresden-leubnitz"]}]}}
```
But if we use the SuggestComponent:
```
/suggest?suggest.build=false&suggest.q=dresde&&suggest=true&suggest.dictionary=suggest&wt=json
{
  "responseHeader":{
    "status":0,
    "QTime":0}}
```
(Mind the missing `q=` paramter!

### Conclusion

There are two errors in the code:
1. We cannot use the SuggestComponent if we do not modify the solrconfig.xml
2. For emty results (empty array) the JavaScript code fails. There must be a check if  we may iterate with each or not.

**Review by albig — CHANGES_REQUESTED** [review]
The autosuggest feature doesn't work like this. The other features seems to work as expected.

File: Resources/Public/Javascript/Search/Suggester.js (hunk 8 above)
Comment (sebastian-meyer) [reply Resources/Public/Javascript/Search/Suggester.js]: Well, I actually forgot to use the `solrconfig.xml` from Kitodo when testing the autocompletion, but used the default Solr configuration and some hand-picked sample data instead.
I'll set up a proper testing environment and take a look at this again - but not today. ;)

Comment (sebastian-meyer) [reply Resources/Public/Javascript/Search/Suggester.js]: I replaced the suggester query with the old dedicated `/suggest` request handler. It's bad design, but the only way without losing backwards compatibility...

File: Classes/Plugin/Eid/SearchSuggest.php [hunk 9]
```diff
@@ -39,25 +38,34 @@ class SearchSuggest
...
+        $solr = Solr::getInstance($core);
+        if ($solr->ready) {
+            $query = $solr->service->createSelect();
+            $query->setHandler('suggest');
+            $query->setQuery(Solr::escapeQuery((string) $parameters['q']));
+            $query->setRows(0);
+            $results = $solr->service->select($query)->getResponse()->getBody();
+            $result = json_decode($results);
+            foreach ($result->spellcheck->suggestions as $suggestions) {
+                foreach ($suggestions->suggestion as $suggestion) {
```
Comment (albig) [inline Classes/Plugin/Eid/SearchSuggest.php]: This does through an exception because the first array element is no object.

That's because of the result of json_decode().
Response from Solr:
`/suggest?q=dresde&json.nl=flat&omitHeader=true&fl=*,score&start=0&rows=0&wt=json`
```
{
  "spellcheck":{
    "suggestions":[
      "dresde",{
        "numFound":2,
        "startOffset":0,
        "endOffset":6,
        "suggestion":["dresdener pflasterstein-werke aktiengesellschaft, dresden-leubnitz",
          "dresden-leipziger schnellpressenfabrik ag, coswig"]}]}}
```
Result of json_decode():
```
object(stdClass)#3 (1) {
  ["spellcheck"]=>
  object(stdClass)#2 (1) {
    ["suggestions"]=>
    array(2) {
      [0]=>
      string(6) "dresde"
      [1]=>
      object(stdClass)#1 (4) {
        ["numFound"]=>
        int(2)
        ["startOffset"]=>
        int(0)
        ["endOffset"]=>
        int(6)
        ["suggestion"]=>
        array(2) {
          [0]=>
          string(66) "dresdener pflasterstein-werke aktiengesellschaft, dresden-leubnitz"
          [1]=>
          string(49) "dresden-leipziger schnellpressenfabrik ag, coswig"
        }
      }
    }
  }
}

```
If we use json_decode with the optional paramter to get an associative array, the result would be:
```
array(1) {
  ["spellcheck"]=>
  array(1) {
    ["suggestions"]=>
    array(2) {
      [0]=>
      string(6) "dresde"
      [1]=>
      array(4) {
        ["numFound"]=>
        int(2)
        ["startOffset"]=>
        int(0)
        ["endOffset"]=>
        int(6)
        ["suggestion"]=>
        array(2) {
          [0]=>
          string(66) "dresdener pflasterstein-werke aktiengesellschaft, dresden-leubnitz"
          [1]=>
          string(49) "dresden-leipziger schnellpressenfabrik ag, coswig"
        }
      }
    }
  }
}

```
So we must check for a valid object or array before calling the foreach() loop.

File: Classes/Plugin/Eid/SearchSuggest.php [hunk 10]
```diff
@@ -39,25 +38,34 @@ class SearchSuggest
...
+                    $output[] = $suggestion;
+                }
```
Comment (albig) [inline Classes/Plugin/Eid/SearchSuggest.php]:
```suggestion
                if (is_object($suggestions)) {
                    foreach ($suggestions->suggestion as $suggestion) {
                        $output[] = $suggestion;
                    }
                }
```

**Review by albig — CHANGES_REQUESTED** [review]
Despite of the last change request, this seems to work.

So solrconfig.xml has to be reviewed and probably updated anyhow. Maybe we should do this in a coming major release and change to the suggester component then.

There are still two Scrutinizer warnings, I do not understand. It seems to work nevertheless.

**Comment by sebastian-meyer** [comment]
I added the task to rewrite the autocompletion to use the proper suggester component to #454.

**Review by albig — APPROVED** [review]
