### PR TITLE
[MAINTENANCE] Add fallback option for getLLL()

### LINKED ISSUE #916: [BUG] New Tenant Module metadata creation fails
## Description

New Tenant Module metadata creation fails with `Argument 1 passed to Kitodo\Dlf\Domain\Model\Metadata::setLabel() must be of the type string, null given, called in /var/www/typo3/public/typo3conf/ext/dlf/Classes/Controller/Backend/NewTenantController.php on line 212`.

The issue occurs in [getLLL()](https://github.com/kitodo/kitodo-presentation/blob/master/Classes/Controller/Backend/NewTenantController.php#L418). It seams that if there is no entry for given language it looks for an default entry. But in case this one is also missing it returns an empty string witch causes the exception.

This is true for following index names:

- `metadata.identifier`
- `metadata.object_name`
- `metadata.object_alternative_names`
- `metadata.object_location`
- `metadata.geonames`
- `metadata.wikidata`

Are these deprecated keys or are just their translations missing? Either way we may consider adding an additional fallback for such cases. 

This is the dump for the langArray:
```
array(2) {
    ["default"] => array(24) {
        ["metadata.author"] => array(1) {
            [0] => array(2) {
                ["source"] => string(6)"Author"["target"] => string(6)"Author"
            }
        }
        ["metadata.collection"] => array(1) {
            [0] => array(2) {
                ["source"] => string(13)"Collection(s)"["target"] => string(13)"Collection(s)"
            }
        }
        ["metadata.coordinates"] => array(1) {
            [0] => array(2) {
                ["source"] => string(11)"Coordinates"["target"] => string(11)"Coordinates"
            }
        }
        ["metadata.date"] => array(1) {
            [0] => array(2) {
                ["source"] => string(4)"Date"["target"] => string(4)"Date"
            }
        }
        ["metadata.description"] => array(1) {
            [0] => array(2) {
                ["source"] => string(11)"Description"["target"] => string(11)"Description"
            }
        }
        ["metadata.language"] => array(1) {
            [0] => array(2) {
                ["source"] => string(8)"Language"["target"] => string(8)"Language"
            }
        }
        ["metadata.license"] => array(1) {
            [0] => array(2) {
                ["source"] => string(7)"License"["target"] => string(7)"License"
            }
        }
        ["metadata.opac_id"] => array(1) {
            [0] => array(2) {
                ["source"] => string(15)"OPAC Identifier"["target"] => string(15)"OPAC Identifier"
            }
        }
        ["metadata.out_of_print"] => array(1) {
            [0] => array(2) {
                ["source"] => string(18)"Out Of Print Works"["target"] => string(18)"Out Of Print Works"
            }
        }
        ["metadata.owner"] => array(1) {
            [0] => array(2) {
                ["source"] => string(5)"Owner"["target"] => string(5)"Owner"
            }
        }
        ["metadata.place"] => array(1) {
            [0] => array(2) {
                ["source"] => string(20)"Place of Publication"["target"] => string(20)"Place of Publication"
            }
        }
        ["metadata.prod_id"] => array(1) {
            [0] => array(2) {
                ["source"] => string(21)"Kitodo Process Number"["target"] => string(21)"Kitodo Process Number"
            }
        }
        ["metadata.purl"] => array(1) {
            [0] => array(2) {
                ["source"] => string(4)"PURL"["target"] => string(4)"PURL"
            }
        }
        ["metadata.record_id"] => array(1) {
            [0] => array(2) {
                ["source"] => string(14)"OAI Identifier"["target"] => string(14)"OAI Identifier"
            }
        }
        ["metadata.restrictions"] => array(1) {
            [0] => array(2) {
                ["source"] => string(22)"Restrictions on Access"["target"] => string(22)"Restrictions on Access"
            }
        }
        ["metadata.rights_info"] => array(1) {
            [0] => array(2) {
                ["source"] => string(18)"Rights Information"["target"] => string(18)"Rights Information"
            }
        }
        ["metadata.terms"] => array(1) {
            [0] => array(2) {
                ["source"] => string(12)"Terms of Use"["target"] => string(12)"Terms of Use"
            }
        }
        ["metadata.title"] => array(1) {
            [0] => array(2) {
                ["source"] => string(5)"Title"["target"] => string(5)"Title"
            }
        }
        ["metadata.type"] => array(1) {
            [0] => array(2) {
                ["source"] => string(4)"Type"["target"] => string(4)"Type"
            }
        }
        ["metadata.union_id"] => array(1) {
            [0] => array(2) {
                ["source"] => string(16)"Union Catalog ID"["target"] => string(16)"Union Catalog ID"
            }
        }
        ["metadata.urn"] => array(1) {
            [0] => array(2) {
                ["source"] => string(3)"URN"["target"] => string(3)"URN"
            }
        }
        ["metadata.volume"] => array(1) {
            [0] => array(2) {
                ["source"] => string(6)"Volume"["target"] => string(6)"Volume"
            }
        }
        ["metadata.year"] => array(1) {
            [0] => array(2) {
                ["source"] => string(19)"Year of Publication"["target"] => string(19)"Year of Publication"
            }
        }
        ["metadata.shelfmark"] => array(1) {
            [0] => array(2) {
                ["source"] => string(9)"Shelfmark"["target"] => string(9)"Shelfmark"
            }
        }
    }
    ["de"] => array(24) {
        ["metadata.author"] => array(1) {
            [0] => array(2) {
                ["source"] => string(6)"Author"["target"] => string(5)"Autor"
            }
        }
        ["metadata.collection"] => array(1) {
            [0] => array(2) {
                ["source"] => string(13)"Collection(s)"["target"] => string(12)"Sammlung(en)"
            }
        }
        ["metadata.coordinates"] => array(1) {
            [0] => array(2) {
                ["source"] => string(11)"Coordinates"["target"] => string(16)"Geoinformationen"
            }
        }
        ["metadata.date"] => array(1) {
            [0] => array(2) {
                ["source"] => string(4)"Date"["target"] => string(5)"Datum"
            }
        }
        ["metadata.description"] => array(1) {
            [0] => array(2) {
                ["source"] => string(11)"Description"["target"] => string(12)"Beschreibung"
            }
        }
        ["metadata.language"] => array(1) {
            [0] => array(2) {
                ["source"] => string(8)"Language"["target"] => string(7)"Sprache"
            }
        }
        ["metadata.license"] => array(1) {
            [0] => array(2) {
                ["source"] => string(7)"License"["target"] => string(6)"Lizenz"
            }
        }
        ["metadata.opac_id"] => array(1) {
            [0] => array(2) {
                ["source"] => string(15)"OPAC Identifier"["target"] => string(15)"OPAC-Identifier"
            }
        }
        ["metadata.out_of_print"] => array(1) {
            [0] => array(2) {
                ["source"] => string(18)"Out Of Print Works"["target"] => string(17)"Vergriffene Werke"
            }
        }
        ["metadata.owner"] => array(1) {
            [0] => array(2) {
                ["source"] => string(5)"Owner"["target"] => string(8)"Besitzer"
            }
        }
        ["metadata.place"] => array(1) {
            [0] => array(2) {
                ["source"] => string(20)"Place of Publication"["target"] => string(15)"Erscheinungsort"
            }
        }
        ["metadata.prod_id"] => array(1) {
            [0] => array(2) {
                ["source"] => string(21)"Kitodo Process Number"["target"] => string(21)"Kitodo-Vorgangsnummer"
            }
        }
        ["metadata.purl"] => array(1) {
            [0] => array(2) {
                ["source"] => string(4)"PURL"["target"] => string(4)"PURL"
            }
        }
        ["metadata.record_id"] => array(1) {
            [0] => array(2) {
                ["source"] => string(14)"OAI Identifier"["target"] => string(14)"OAI-Identifier"
            }
        }
        ["metadata.restrictions"] => array(1) {
            [0] => array(2) {
                ["source"] => string(22)"Restrictions on Access"["target"] => string(21)"Zugriffsinformationen"
            }
        }
        ["metadata.rights_info"] => array(1) {
            [0] => array(2) {
                ["source"] => string(18)"Rights Information"["target"] => string(17)"Rechteinformation"
            }
        }
        ["metadata.shelfmark"] => array(1) {
            [0] => array(2) {
                ["source"] => string(9)"Shelfmark"["target"] => string(8)"Signatur"
            }
        }
        ["metadata.terms"] => array(1) {
            [0] => array(2) {
                ["source"] => string(12)"Terms of Use"["target"] => string(19)"Nutzungsbedingungen"
            }
        }
        ["metadata.title"] => array(1) {
            [0] => array(2) {
                ["source"] => string(5)"Title"["target"] => string(5)"Titel"
            }
        }
        ["metadata.type"] => array(1) {
            [0] => array(2) {
                ["source"] => string(4)"Type"["target"] => string(11)"Strukturtyp"
            }
        }
        ["metadata.union_id"] => array(1) {
            [0] => array(2) {
                ["source"] => string(16)"Union Catalog ID"["target"] => string(18)"Verbund-Identifier"
            }
        }
        ["metadata.urn"] => array(1) {
            [0] => array(2) {
                ["source"] => string(3)"URN"["target"] => string(3)"URN"
            }
        }
        ["metadata.volume"] => array(1) {
            [0] => array(2) {
                ["source"] => string(6)"Volume"["target"] => string(4)"Band"
            }
        }
        ["metadata.year"] => array(1) {
            [0] => array(2) {
                ["source"] => string(19)"Year of Publication"["target"] => string(16)"Erscheinungsjahr"
            }
        }
    }
}
```

## Reproduction

Steps to reproduce the behaviour:

1. Go to BE -> Admin Tools -> New Tenant -> _your presentation config folder_
2. click on create metadata

## Expected Behavior

no error

## Environment

 - OS version: Debian
 - RDBMS version: Maria DB (MySQL 5.5.5-10.9.3-MariaDB-1:10.9.3+maria~ubu2204 )
 - Apache Solr version: 8.11.2
 - TYPO3 version: 10.4.37-dev
 - PHP version: 7.4.33

### PR DESCRIPTION
**Pull request by csidirop**
This PR implements a fallback option in getLLL() if there is no translation for given key as proposed in https://github.com/kitodo/kitodo-presentation/issues/916

After creating metadata with missing strings:
grafik

But endusers can still change the title to their needings:
grafik

### CODE REVIEW

**Comment by csidirop** [comment]
Updated commit to meet Codacy Productions static code analysis requirements

File: Classes/Controller/Backend/NewTenantController.php [hunk 1]
```diff
@@ -419,8 +419,10 @@ protected function getLLL($index, $lang, $langArray)
     {
         if (isset($langArray[$lang][$index][0]['target'])) {
             return $langArray[$lang][$index][0]['target'];
-        } else {
+        } else if (isset($langArray['default'][$index][0]['target'])) {
```
Comment (sebastian-meyer) [inline Classes/Controller/Backend/NewTenantController.php]:
```suggestion
        } elseif (isset($langArray['default'][$index][0]['target'])) {
```

File: Classes/Controller/Backend/NewTenantController.php [hunk 2]
```diff
@@ -419,8 +419,10 @@ protected function getLLL($index, $lang, $langArray)
...
             return $langArray['default'][$index][0]['target'];
+        } else {
+            return "Missing translation for ".substr($index, 9); //cut 'metadata.' string
```
Comment (sebastian-meyer) [inline Classes/Controller/Backend/NewTenantController.php]: Since this method is not only used for metadata, but also for structure labels, the `substr()` function would not work as intended. I'd be fine with just using the whole translation key here:
```suggestion
            return 'Missing translation for ' . $index;
```
What do you think?

**Review by sebastian-meyer — CHANGES_REQUESTED** [review]

File: Classes/Controller/Backend/NewTenantController.php (hunk 2 above)
Comment (csidirop) [reply Classes/Controller/Backend/NewTenantController.php]: Ok I didn't knew that. Your suggestion looks fine to me.

**Review by sebastian-meyer — APPROVED** [review]
Thank you!
