### PR TITLE
[BUGFIX] Fix indexing regression (issue #1664)

### LINKED ISSUE #1664: [BUG] Indexing reports missing required metadata field "record_id" in release 5.1.0
## Description

See issue #1550.

## Reproduction

See issue #1550.

### PR DESCRIPTION
**Pull request by stweil**
This is a backport of the commits 30976d4 and d310ed5.

### CODE REVIEW

**Comment by stweil** [comment]
With these backports I now get a different message:
```
# vendor/bin/typo3 kitodo:index --pid=3 --solr=dlfCore0 --doc=https://digital.ladenburg.de/data/Ladenburger_Wochenblatt/mets18690415.xml

Index single document into database and Solr.
=============================================

 [ERROR] ERROR: Document with UID "7" could not be indexed on Solr core 2. Check TYPO3 log for more details.            

 [INFO] INFO: Document with UID "7" is already in database. If you want to keep the database and index consistent you   
        need to remove it.
```

The TYPO3 log still shows errors:
```
Wed, 09 Jul 2025 07:28:14 +0200 [ERROR] request="362ecc9695d35" component="Kitodo.Dlf.Validation.DocumentValidator": Missing required metadata field "record_id". 
Wed, 09 Jul 2025 07:28:14 +0200 [ERROR] request="362ecc9695d35" component="Kitodo.Dlf.Common.Helper": There are missing mandatory fields (at least one of those: document_format,record_id) in this document 
Wed, 09 Jul 2025 07:28:14 +0200 [ERROR] request="362ecc9695d35" component="Kitodo.Dlf.Validation.DocumentValidator": Missing required metadata field "record_id". 
Wed, 09 Jul 2025 07:28:14 +0200 [ERROR] request="362ecc9695d35" component="Kitodo.Dlf.Common.Helper": There are missing mandatory fields (at least one of those: document_format,record_id) in this document 
Wed, 09 Jul 2025 07:28:14 +0200 [ERROR] request="362ecc9695d35" component="Kitodo.Dlf.Validation.DocumentValidator": Missing required metadata field "record_id". 
Wed, 09 Jul 2025 07:28:14 +0200 [ERROR] request="362ecc9695d35" component="Kitodo.Dlf.Common.Helper": There are missing mandatory fields (at least one of those: document_format,record_id) in this document 
```

**Comment by stweil** [comment]
@beatrycze-volk, although I backported two of your commits which were related to the old issue #1550, indexing still shows error messages. Did I miss other commits which are still needed? Or do you have another idea what might be missing in 5.1.x?

**Comment by beatrycze-volk** [comment]
Actually I have changed this again:

https://github.com/kitodo/kitodo-presentation/pull/1647/files
https://github.com/kitodo/kitodo-presentation/pull/1666/files

As the list of types is too long to really be handled as condition for exclusion.

**Comment by stweil** [comment]
> Actually I have changed this again [...]

I backported these recent commits now, too, and have updated this pull request.

**Comment by beatrycze-volk** [comment]
Did it work for you? We were able with those changes index documents in one of our portals.

**Comment by stweil** [comment]
No, I still get the error messages listed above. Maybe indexing works for some kinds of documents, but fails for others? Did you try to index one of my newspaper issues (see URL above)?

**Comment by sebastian-meyer** [comment]
How shall we proceed with this PR?

**Comment by stweil** [comment]
I am not sure whether these changes should be applied unless they fix the indexing issue at least for some documents. @beatrycze-volk, did indexing work for you with my documents?

**Comment by fschoelzel** [comment]
Hey @stweil ,
I try to figure out the Issue with your Document:
https://digital.ladenburg.de/data/Ladenburger_Wochenblatt/mets18690415.xml

Have a try indexing the Document with the Branch of my Pull Request #1683 
With this Branch https://github.com/fschoelzel/kitodo-presentation/tree/fix-filter-fulltext-for-physSequence
I didn't took the changes from your PR.

This works in my case. It is necessary to have the right Metadata Definitions in the Kitodo Folder in your Backend. 
For example:
The Metadata with Index_Name: `record_id` 
needs to have this MODS xpath selector: `./mods:recordInfo/mods:recordIdentifier`
Have a look into the Logs if any Definition is missing.
Sometimes it helps to remove all Metadata and Data-Formats and generate them from scratch with the Kitodo "New Tenant" Module.

Bildschirmfoto vom 2025-08-08 15-09-07

**Comment by stweil** [comment]
Thank you, @fschoelzel. I'll test it later.

**Comment by sebastian-meyer** [comment]
@stweil Please check, if #1680 fixed your issue.

**Comment by stweil** [comment]
@fschoelzel, after I removed all "Metadata" list entries and created them again with "New Tenant", indexing now works fine.

@sebastian-meyer, @beatrycze-volk, I think this pull request is ready for merging. My personal [5.1.x branch](https://github.com/stweil/kitodo-presentation/tree/5.1.x) which I use for [my test installation](https://digital.ladenburg.world/kitodo/) includes some more commits which address PHP warnings and OAI issues. For these commits I'll create separate pull requests.

**Review by beatrycze-volk — APPROVED** [review]

File: Classes/Common/MetsDocument.php [hunk 1]
```diff
@@ -567,6 +567,16 @@ private function getMetadataFromArray(string $id, int $cPid): array
         if (!empty($this->metadataArray[$id]) && $this->metadataArray[0] == $cPid) {
             return $this->metadataArray[$id];
         }
+
+        $administrativeNode = $this->mets->xpath('./mets:structMap[@TYPE="LOGICAL"]//mets:div[@ADMID]/@ID');
+
+        if (!empty($administrativeNode)) {
+            $administrativeId = (string)$administrativeNode[0];
```
Comment (sebastian-meyer) [inline Classes/Common/MetsDocument.php]:
```suggestion
            $administrativeId = (string) $administrativeNode[0];
```

**Review by sebastian-meyer — APPROVED** [review]
